[package]
name = "pair"
version = "1.0.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "pair"
path = "src/main.rs"

[dependencies]
casper-contract.workspace = true
casper-types.workspace = true
