[package]
name = "test-minimal"
version = "1.0.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "test_minimal"
path = "src/main.rs"
bench = false
doctest = false
test = false

[dependencies]
casper-contract.workspace = true
casper-types.workspace = true
